server:
  port: 8050
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka
zuul:
  routes:
    app-provider-user:
      path: /user/**
      serviceId: provider-user
    app-sidecar:
      path: /sidecar/**
      serviceId: sidecar